apiVersion : apps/v1
kind: Deployment
metadata:
  name: jobservice 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jobservice
  template:
    metadata:
      labels:
        app: jobservice 
    spec:
      containers:
        - name: jobservice 
          image: myappreg123.azurecr.io/jobservice
          ports:
          - containerPort: 8000